regular:
  - angle-left
  - angle-right
  - arrow-right
  - bars
  - check
  - check-double
  - chevron-right
  - ellipsis-vertical
  - eye
  - magnifying-glass
  - pencil
  - print
  - trash
  - truck
  - users
  - xmark