light:
  - angle-left
  - angle-right
  - arrow-right
  - bars
  - cart-shopping
  - check
  - check-double
  - chevron-right
  - credit-card
  - ellipsis-vertical
  - eye
  - list
  - location-dot
  - magnifying-glass
  - pencil
  - person-dolly
  - person-dolly-empty
  - play
  - print
  - right-long
  - signs-post
  - stop
  - trash
  - truck
  - users
  - xmark
regular:
  - angle-left